//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.DeThi_ChiTiets = new HashSet<DeThi_ChiTiets>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdMonHoc { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<int> GvTao { get; set; }
        public Nullable<byte> DaDuyet { get; set; }
        public Nullable<byte> DaXoa { get; set; }
        public Nullable<int> IdNhom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi_ChiTiets> DeThi_ChiTiets { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual NhomDeThi NhomDeThi { get; set; }
    }
}
