//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public string IdThanhVien { get; set; }
        public long IdCauHoi_DeThi { get; set; }
        public string DapAn { get; set; }
        public Nullable<byte> DaXoa { get; set; }
    
        public virtual DeThi_ChiTiets DeThi_ChiTiets { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
